---
- hosts: all
  become: true
  
  tasks:
       - name: Install apache2
         apt: name=apache2 state=present

       - name: start apache
         service: name=apache2 state=started enabled=yes

